version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-ctf
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: ctf
      POSTGRES_DB: ctfdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-ctf
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # 영속성도 ON
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
