version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-ctf
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: ctf
      POSTGRES_DB: ctfdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
