spring:
  application:
    name: guardians


  config:
    import: vault://

  cloud:
    vault:
      uri: ${VAULT_URI}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: guardians
        profile-separator: '/'
      fail-fast: true
      config:
        lifecycle:
          enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  session:
    store-type: redis
    timeout: 1800s
    cookie:
      name : JSESSIONID
      same-site: none
      secure: ${COOKIE_SESSION}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

cloud:
  aws:
    s3:
      bucket: guardians-bucket-name
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
    default-profile-url: ${DEFAULT_PROFILE_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.boot.context.config: DEBUG